name: material_elements
description: A pub package
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
  sass: any
transformers:
- sass
- polymer:
    inline_stylesheets: false
    entry_points:
      - example/index.html
      - example/material_card/index.html
